### ISSUE TITLE
Using str::len for bio length validation is problematic.

### ISSUE THREAD

**Issue by TheRawMeatball** [bevyengine/bevy-community#20]
`str::len` measures length in bytes, not characters, and as such things like emojis and other non-ascii characters will count for more than they should. This function is inappropriate for this use case.

**Comment by TheRawMeatball** [comment]
A fix could be to use `s.chars().count()` instead, though as pointed out by this stackoverflow question, https://stackoverflow.com/questions/46290655/get-the-string-length-in-characters-in-rust, that is also susceptible. This answer suggests using the crate `https://crates.io/crates/unicode-segmentation` to iterate over graphemes instead and count those.

**Comment by cart** [comment]
Just switched the community pull request over to the unicode-segmentation / grapheme count approach. Nice catch!
